<?php

/**
 * Implementation of hook_field_formatter_info().
 */
function textfieldlink_field_formatter_info() {
  return array(
    'textfieldlink' => array(
      'label' => t('Text field link'),
      'field types' => array('text'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}


function theme_textfieldlink_formatter_textfieldlink($element) {
  $output = '';
  if (!empty($element['#item']['value'])) {
    $field = content_fields($element['#field_name'],$element['#node']->type);
    $output = l($field['widget']['label'], 'node/'. $element['#node']->nid.'/text/'.$element['#field_name']);
  }
  return $output;
}

/**
 * Implementation of hook_theme().
 */
function textfieldlink_theme() {
  return array(
    'textfieldlink_formatter_textfieldlink' => array(
      'arguments' => array('element'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function textfieldlink_menu() {
  return array(
    'node/%node/text/%' => array(
    'title' => 'Text field',
    'description' => 'A textfield\s text',
    'page callback' => 'textfieldlink_page',
    'page arguments' => array(1,3),
    'access callback' => 'textfieldlinkaccess',
    'access arguments' => array(1,3),
    )
  );
}

function textfieldlinkaccess($node,$field_name) {
  $field = content_fields($field_name);
  return content_access('view',$field,NULL,$node);
}

function textfieldlink_page($node,$field_name) {
  $link = '<div>'.t("Return to !node",array('!node'=>l($node->title,'node/'.$node->nid))).'</div>';
  $field = content_fields($field_name,$node->type);
  drupal_set_title($field['widget']['label']);
   $db_info = content_database_info($field);
  $item = array();
  $item['value'] =$node->{$field_name}[0]['value'];
  $item['#delta'] =  0;
  $item['#node'] = $node;
  // Render items.
  $formatter_name = 'default';
  if ($formatter = _content_get_formatter($formatter_name, $field['type'])) {
    
    if (content_handle('formatter', 'multiple values', $formatter) == CONTENT_HANDLE_CORE) {
      // Single-value formatter.
      $output = content_format($field, $item, $formatter_name, $node);
    }
    else {
      // Multiple values formatter - we actually have only one value to display.
      $output = content_format($field, array($item), $formatter_name, $node);
    }
    return $output . $link;
  }
  return '' . $link;

}